### ISSUE TITLE
Life-forms

### ISSUE THREAD

**Issue by axmanovairena** [Kryshtoson/CZE_Expansive-species-list#2]
We need to change the names of the categories to english - Therophyte etc. Sorry was not in the input table.

**Comment by axmanovairena** [comment]
Maybe in the graph we do not need to have Therophyte on both sides of the bar, can be just next to each row once? And rather to indicate all species and expansive instead?

**Comment by Kryshtoson** [comment]
> We need to change the names of the categories to english - Therophyte etc. Sorry was not in the input table.

I edited it in the main table on cloud.

**Comment by Kryshtoson** [comment]
> Maybe in the graph we do not need to have Therophyte on both sides of the bar, can be just next to each row once? And rather to indicate all species and expansive instead?

Yes, makes sense. I changed it now also elsewhere.
